# Generated by Django 5.2.1 on 2025-05-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_reference_number", models.CharField(max_length=50)),
                ("passenger_mobile_number", models.CharField(max_length=20)),
                ("pickup_address", models.CharField(max_length=255)),
                ("destination_address", models.CharField(max_length=255)),
                ("item_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("found", "Found"),
                            ("not_found", "Not Found"),
                            ("driver_unreachable", "Driver Unreachable"),
                            ("verified", "Verified"),
                            ("delivered", "Delivered"),
                            ("picked_from_office", "Picked from Office"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
